#!/bin/bash

#Run gazebo, this file is responsible for changing enviroment
roslaunch velmaverse velmaverse.launch &
PIDGAZ=$!

# chagning geometry_msgs/Twist to omnivelma/Vels and publishing
rosrun transmutator transmutator /omnivelma/vels #/widelnica/vels &
PIDTRA=$!

# changing encoder msg type
rosrun dziadzio dziadzio /omnivelma/encoders /lalkarz/encoders &
PIDDZI=$!

trap "kill $PIDDZI; kill $PIDTRA; kill $PIDGAZ;" SIGINT 

echo "Wciśnij ^C, aby wyłączyć procesy"
# sleep infinity
